# Generated by Django 3.2.1 on 2023-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20230331_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
