# Generated by Django 3.2.1 on 2023-04-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_participant_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='countdownTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='questionNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Question'), (3, 'Answer'), (4, 'Leaderboard')], default=5),
        ),
    ]
