# Generated by Django 3.2.1 on 2023-04-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_alter_game_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-updated_at']},
        ),
    ]
