# Generated by Django 3.2.1 on 2023-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_question_answertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
