# Generated by Django 3.2.1 on 2023-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_participant_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
