# Generated by Django 3.2.1 on 2023-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20230410_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='publicId',
            field=models.IntegerField(unique=True),
        ),
    ]
