# Generated by Django 3.2.1 on 2023-04-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_game_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['points']},
        ),
    ]
