# Generated by Django 3.2.1 on 2023-04-29 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_participant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-points']},
        ),
    ]
